using NUnit.Framework;

using NLog;
using Giis.Portable.Util;
using Giis.Selema.Manager;
using Giis.Selema.Portable.Selenium;
using Giis.Selema.Services;
using Giis.Selema.Services.Impl;
using Test4giis.Selema.Portable;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
/////// THIS FILE HAS BEEN AUTOMATICALLY CONVERTED FROM THE JAVA SOURCES. DO NOT EDIT ///////

namespace Test4giis.Selema.Video
{
    /// <summary>
    /// Partially integrated test of a Video Controller (local).
    /// 
    /// Tests are integrated with docker and do not need any external sever,
    /// but mock the video recorder using a lightweight
    /// container. To be run in an independent workflow to run in CI.
    /// </summary>
    public class TestVideoControllerLocal
    {
        static readonly Logger log = LogManager.GetCurrentClassLogger(); //TestVideoControllerLocal));
        private static readonly string MOCK_CONTAINER = "selenium-video-mock";
        private static readonly string MOCK_IMAGE = "selenium-video-mock-image";
        private static readonly string ROOT = Parameters.GetProjectRoot(); // for .NET compatibility
        private static readonly string REPORTS = FileUtil.GetPath(ROOT, Parameters.GetReportSubdir());
        // note that the build context is platform independent, located in the java project
        private static readonly string DOCKER_BUILD_CONTEXT = FileUtil.GetPath(ROOT, "../java", "src/test/resources/vcmock");
        private static readonly string MAPPED_FOLDER = FileUtil.GetPath(REPORTS, "selema/vcmock-mapped");
        private static readonly string RECORDED_VIDEO = MAPPED_FOLDER + "/video.mp4";
        private static readonly string TARGET_FOLDER = FileUtil.GetPath(REPORTS, "selema/vcmock-target");
        
        [NUnit.Framework.OneTimeSetUp]
        public static void SetUpAll()
        {
            log.Debug("Building the mock video recorder docker container");
            string buildCommand = "docker build -t " + MOCK_IMAGE + " " + DOCKER_BUILD_CONTEXT;
            System.Console.WriteLine(buildCommand);
            Run(buildCommand);
        }

        [NUnit.Framework.SetUp]
        public virtual void SetUp()
        {
            log.Info("****** Running test: {} ******", NUnit.Framework.TestContext.CurrentContext.Test.Name);

            // Ensures a clean environment for both container and video files and folders
            Run("docker stop " + MOCK_CONTAINER);
            Run("docker rm " + MOCK_CONTAINER);
            FileUtil.CreateDirectory(MAPPED_FOLDER);
            FileUtil.CreateDirectory(TARGET_FOLDER);
            FileUtil.DeleteFilesInDirectory(MAPPED_FOLDER);
            FileUtil.DeleteFilesInDirectory(TARGET_FOLDER);
            log.Info("Test setup done");
        }

        protected virtual IVideoController GetController()
        {
            return new VideoControllerLocal(MOCK_CONTAINER, RECORDED_VIDEO, TARGET_FOLDER);
        }

        protected static void Run(string command)
        {
            string output = CommandLine.RunCommand(command);
            System.Console.WriteLine(output.Trim());
        }

        // This mocks what the external script will do to preload the containers, with some additional verification
        protected virtual void PreloadRecorder(bool stopAfterRun)
        {
            string mappedVolume = FileUtil.GetFullPath(MAPPED_FOLDER);
            mappedVolume = mappedVolume.Replace("\\", "/").Replace("C:/", "//c/"); // fix for windows
            string runCommand = "docker run -d --name " + MOCK_CONTAINER + " -v " + mappedVolume + ":/app/videos " + MOCK_IMAGE;
            System.Console.WriteLine(runCommand);
            Run(runCommand);
            ContainerUtil.WaitDocker(MOCK_CONTAINER, "Display", "is open", 5);
            Asserts.AssertIsTrue(CommandLine.FileExists(RECORDED_VIDEO), "Video file generated by the mock container after preload does not exist");
            if (stopAfterRun)
            {
                ContainerUtil.RunDocker("stop", MOCK_CONTAINER);
                ContainerUtil.WaitDocker(MOCK_CONTAINER, "Shutdown complete", "", 5);
            }
        }

        [Test]
        public virtual void TestPassRegularLifeCycle()
        {

            // Preload creates a video, but in the regular lifecycle, the recorded video should have been deleted after copy
            PreloadRecorder(true);
            CommandLine.FileDelete(RECORDED_VIDEO, true);
            Asserts.AssertIsTrue(!CommandLine.FileExists(RECORDED_VIDEO), "Video file generated by the mock should have been deleted by this test");
            DoTestLifeCycle();
        }

        [Test]
        public virtual void TestPassWhenPreviousRunDidNotDeleteVideo()
        {

            // This is the situation just after preload
            PreloadRecorder(true);
            DoTestLifeCycle();
        }

        [Test]
        public virtual void TestPassWhenPreviousRunDidNotStopRecorder()
        {

            // To simulate that the previous run did not stop the container, do preload without stopping container
            PreloadRecorder(false);

            // When we start a container that is started, there is no action, therefore no new video is created.
            // To simulate this situation, we delete now the video:
            // If the controller does not restart the container in this situation, no new video will be created
            // at the start will fail because video is not present during lifecycle
            CommandLine.FileDelete(RECORDED_VIDEO, true);
            Asserts.AssertIsTrue(!CommandLine.FileExists(RECORDED_VIDEO), "Video file generated by the mock should have been deleted by this test");
            DoTestLifeCycle();
        }

        protected virtual void DoTestLifeCycle()
        {
            IVideoController vc = GetController();
            vc.Start();
            Asserts.AssertIsTrue(CommandLine.FileExists(RECORDED_VIDEO), "Video file should be present during the lifecycle");
            vc.Stop("copied-video.mp4");

            // The video should have been copied to target and removed from the mapped volume, and the container stopped
            Asserts.AssertIsTrue(!CommandLine.FileExists(RECORDED_VIDEO), "Video file generated by the mock container should have been removed");
            Asserts.AssertIsTrue(CommandLine.FileExists(TARGET_FOLDER + "/copied-video.mp4"), "Video file to be copied to the target folder does not exist");
            NUnit.Framework.Legacy.ClassicAssert.AreEqual("exited", ContainerUtil.GetContainerStatus(MOCK_CONTAINER));
        }

        [Test]
        public virtual void TestFailOnStartBecauseRecorderDoesNotExist()
        {

            // Do not preload, so that the containers are missing
            Exception e = NUnit.Framework.Assert.Throws(typeof(SelemaException), () =>
            {
                IVideoController vc = GetController();
                vc.Start();
            });
            Asserts.AssertContains("No such container", e.Message);
        }

        [Test]
        public virtual void TestFailOnStopBecauseCanNotCopyVideo()
        {

            // This is a common situation when the controller can't access to the recorded video
            // (usually because of file permissions). Simulated by deleting the video before stop
            PreloadRecorder(true);
            IVideoController vc = GetController();
            vc.Start();
            CommandLine.FileDelete(RECORDED_VIDEO, true);
            Exception e = NUnit.Framework.Assert.Throws(typeof(PortableException), () =>
            {
                vc.Stop("not-copied-video.mp4");
            });
            Asserts.AssertContains("Can't copy", e.Message);
        }

        [Test]
        public virtual void TestFailOnStopBecauseCanNotStopRecorder()
        {

            // Not likely, but the recorder could fail in the middle of the process and be unable to be stopped
            // Simulated by removing the container before stop
            PreloadRecorder(true);
            IVideoController vc = GetController();
            vc.Start();
            Run("docker stop " + MOCK_CONTAINER);
            Run("docker rm " + MOCK_CONTAINER);
            Exception e = NUnit.Framework.Assert.Throws(typeof(SelemaException), () =>
            {
                vc.Stop("not-copied-video2.mp4");
            });
            Asserts.AssertContains("No such container", e.Message);
        }

        [Test]
        public virtual void TestContainerNotReadyAfterWaitForLogMessage()
        {

            // To complement the above, check that the waiting for the container log is able to fail after timeout
            Run("docker run -d --name " + MOCK_CONTAINER + " " + MOCK_IMAGE);
            Exception e = NUnit.Framework.Assert.Throws(typeof(SelemaException), () =>
            {
                ContainerUtil.WaitDocker(MOCK_CONTAINER, "Other docker log message", "that is not present", 1);
            });
            Asserts.AssertContains("Container did not become ready in time", e.Message);
        }
    }
}