package test4giis.selema.video;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import giis.portable.util.FileUtil;
import giis.selema.manager.SelemaException;
import giis.selema.portable.selenium.CommandLine;
import giis.selema.services.IVideoController;
import giis.selema.services.impl.ContainerUtil;
import giis.selema.services.impl.VideoControllerLocal;
import test4giis.selema.portable.Asserts;

/**
 * Partially integrated test of the main actions (start, stop) of a Video Controller (local).
 * 
 * Tests are integrated with docker and do not need any external sever, 
 * but mock the video recorder using a lightweight container.
 * Use an independent workflow to run in CI.
 */
public class TestVideoControllerLocal {
	static final Logger log = LoggerFactory.getLogger(TestVideoControllerLocal.class);

	private static final String MOCK_CONTAINER = "mock-recorder";
	private static final String MOCK_IMAGE = "mock-recorder-image";
	private static final String DOCKER_BUILD_CONTEXT = "src/test/resources/vcmock";

	private static final String MAPPED_FOLDER = "target/selema/vcmock-mapped";
	private static final String RECORDED_VIDEO = MAPPED_FOLDER + "/video.mp4";
	private static final String TARGET_FOLDER = "target/selema/vcmock-target";

	@Rule
	public TestName testName = new TestName();

	@BeforeClass
	public static void setUpAll() {
		log.debug("Building mock docker video recorder container");
		String buildCommand = "docker build -t " + MOCK_IMAGE + " " + DOCKER_BUILD_CONTEXT;
		System.out.println(buildCommand);
		run(buildCommand);
	}

	@Before
	public void setUp() {
		log.info("****** Running test: {} ******", testName.getMethodName());
		// Ensures a clean environment for both containers and video files and folders
		run("docker stop " + MOCK_CONTAINER);
		run("docker rm " + MOCK_CONTAINER);
		FileUtil.deleteFilesInDirectory(MAPPED_FOLDER);
		FileUtil.deleteFilesInDirectory(TARGET_FOLDER);
		FileUtil.createDirectory(MAPPED_FOLDER);
		FileUtil.createDirectory(TARGET_FOLDER);
	}

	private static void run(String command) {
		String output = CommandLine.runCommand(command);
		System.out.println(output.trim());
	}

	protected IVideoController getController() {
		return new VideoControllerLocal(MOCK_CONTAINER, RECORDED_VIDEO, TARGET_FOLDER);
	}

	// This mocks what the external script will run to preload the containers, with some additional verification
	private void preloadRecorder(boolean stopAfterRun) {
		String mappedVolume = FileUtil.getFullPath(MAPPED_FOLDER);
		mappedVolume = mappedVolume.replace("\\", "/").replace("C:/", "//c/"); // fix for windows
		
		String runCommand = "docker run -d --name " + MOCK_CONTAINER  
				+ " -v " + mappedVolume + ":/app/videos " + MOCK_IMAGE;
		System.out.println(runCommand);
		run(runCommand);
		ContainerUtil.waitDocker(MOCK_CONTAINER, "Display", "is open", 5);
		Asserts.assertIsTrue(CommandLine.fileExists(RECORDED_VIDEO),
				"Video file generated by the mock container does not exist");
		if (stopAfterRun) {
			ContainerUtil.runDocker("stop", MOCK_CONTAINER);
			ContainerUtil.waitDocker(MOCK_CONTAINER, "Shutdown complete", "", 5);
		}
	}

	@Test
	public void testControllerHappyLifeCycle() {
		preloadRecorder(true);
		IVideoController vc = getController();
		vc.start();
		vc.stop("copied-video.mp4");

		// The recording has been copied to target and removed from the mapped volume, and the container stopped
		Asserts.assertIsTrue(!CommandLine.fileExists(RECORDED_VIDEO),
				"Video file generated by the mock container should have been removed");
		Asserts.assertIsTrue(CommandLine.fileExists(TARGET_FOLDER + "/copied-video.mp4"),
				"Video file to be copied to the target folder does not exist");
		assertEquals("exited", ContainerUtil.getContainerStatus(MOCK_CONTAINER));
	}

	@Test
	public void testContainerDoesNotExistFailsOnStart() {
		RuntimeException e = assertThrows(SelemaException.class, () -> {
			IVideoController vc = getController();
			vc.start();
		});
		Asserts.assertContains("No such container", e.getMessage());
	}

	@Test
	public void testCanNotCopyFileFailsOnStop() {
		preloadRecorder(true);
		IVideoController vc = getController();
		vc.start();
		CommandLine.fileDelete(RECORDED_VIDEO, true);
		RuntimeException e = assertThrows(giis.portable.util.PortableException.class, () -> {
			vc.stop("not-copied-video.mp4");
		});
		Asserts.assertContains("Can't copy", e.getMessage());
	}

	@Test
	public void testContainerNotReadyAfterWaitingLogMessage() {
		run("docker run -d --name " + MOCK_CONTAINER + " " + MOCK_IMAGE);
		RuntimeException e = assertThrows(SelemaException.class, () -> {
			ContainerUtil.waitDocker(MOCK_CONTAINER, "Other docker log message", "that is not present", 1);
		});
		Asserts.assertContains("Container did not become ready in time", e.getMessage());
	}

}