name: docker-selenium-issue-3129
# Time to stop the video container across different versions
on:
  workflow_dispatch:
jobs:
  test:
    defaults:
      run:
        working-directory: selenium-test/test-video-close
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          chmod +x run-test.sh
          ./run-test.sh
